apiVersion: apps/v1
kind: Deployment
metadata:
  name: authormanagement
  labels:
    app: authormanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authormanagement
  template:
    metadata:
      labels:
        app: authormanagement
    spec:
      containers:
        - name: authormanagement
          image: "project01.azurecr.io/authormanagement:prod2"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20      # 앱 부팅 시간 고려
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 20         # 실패 허용 횟수 증가
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
