apiVersion: apps/v1
kind: Deployment
metadata:
  name: authormanagement
  labels:
    app: authormanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authormanagement
  template:
    metadata:
      labels:
        app: authormanagement
    spec:
      containers:
        - name: authormanagement
          image: "project01.azurecr.io/author:test"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
