apiVersion: apps/v1
kind: Deployment
metadata:
  name: subcription
  labels:
    app: subcription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subcription
  template:
    metadata:
      labels:
        app: subcription
    spec:
      containers:
        - name: subcription
          image: "project01.azurecr.io/subscription:v1"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
