apiVersion: apps/v1
kind: Deployment
metadata:
  name: aipublication
  labels:
    app: aipublication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aipublication
  template:
    metadata:
      labels:
        app: aipublication
    spec:
      containers:
        - name: aipublication
          image: project01.azurecr.io/aipublication:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
